### ISSUE TITLE
SPM file is failing to process in 3D Repo

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepobouncer#516]
### Description

One of our users is struggling to upload an SPM file to 3D Repo. After about 3 hours of processing you receive the following error messages:
1. Failed to generate Unity Bundles
2. System error occurred. Please contact support

- This is happening in: prod
- This requires a hotfix to production: depending on its complexity

### Steps to replicate
- Head over to 3drepo.io and upload the following file:
[LAT-JSS-00-ZZ-VS-W-0037.spm](https://www.dropbox.com/s/0tlamm7ye8sv6pg/LAT-JSS-00-ZZ-VS-W-0037.spm?dl=0)
- Wait for 3D Repo to start processing
- Generating bundles appears after a while
- Model import error message appears

### Current Behaviour
- Fails to process SPM file
- Fails to process SPM file with complex geometry removed from it:
[LAT-JSS-00-ZZ-VS-W-0037_No parking or Louvre or Hoarding Fence](https://www.dropbox.com/s/p12izire5lvtz1f/LAT-JSS-00-ZZ-VS-W-0037_No%20parking%20or%20Louvre%20or%20Hoarding%20Fence.spm?dl=0)
- Works fine for static (single frame) SPM exports:
[Single Frame SPM Export files](https://www.dropbox.com/sh/heqpqeaqmsvm28w/AAD4CcLkRIJ1YDV6vYKaqOLTa?dl=0)

### Expected Behaviour
- Process the model and work in 3D Repo

### Pictures/ Gifs of the error
[Original Synchro File](https://www.dropbox.com/s/bntej8z4krjdhiw/LAT-JSS-00-ZZ-VS-W-0037.sp?dl=0)

[Single Frame SPM models in 3drepo.io](www.3drepo.io/viewer/support_3DRepo/ddded6e0-4184-11ec-9f10-6938ae79cbe8)

**Single Frame SPM export in 3D Repo**
![Single Frame](https://user-images.githubusercontent.com/19904513/141327326-9b8455ee-6c74-417b-95a3-c0825e8c9c55.jpg)

**Comment by mosment3DRepo** [comment]
@carmenfan I had a look at the tree in Synchro, it doesn't seem unusually complex. There's a total of 49k elements (including parents) gping down 8 or 9 level.

**Comment by carmenfan** [comment]
This model takes too long because we're generating too many super meshes, due to the nature of this animated sequence forces a lot of meshes to animate on their own. 

For animation to work, we group them into their own super mesh, so each resource ID in synchro would map to their own super mesh. In this instance, there are many resource ID where they only map to a single super mesh, causing a lot of supermeshes to be created (hence timing out in unity)


I'm assuming this is not something we wish to support thus closing this ticket - reopen if necessary
