### ISSUE TITLE
RabbitMQ 3.10 changed behaviour of unacknowledged messages

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepobouncer#585]
### Description

There was an issue on production captured in https://github.com/3drepo/DevOps/issues/457 that was resolved with a configuration change on rabbitmq as they [changed the default behaviour of unacknowledged queues in RabbitMQ 3.10.](https://github.com/rabbitmq/rabbitmq-server/pull/2990) This change was also [backported to 3.8.15](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.15)

They've also deprecated 'classic queues' and recommend new quorum queues [https://www.rabbitmq.com/ha.html](https://www.rabbitmq.com/ha.html)

We are also seeing higher queue numbers as the system gets busier, and unacknowledged messages, due to the high number of channel exceptions, we also encountered [this 'stuck' queue](https://github.com/Particular/NServiceBus.RabbitMQ/issues/843)

> RabbitMQ Uacked Messages are unacknowledged messages. In RabbitMQ, when many messages are delivered to the consumer or the target. But according to protocols, it is not guaranteed that message delivery will always be successful. So to solve this, Publishers and Consumers require a mechanism for delivery and processing confirmation. This is where Acknowledgement and Unacknowledgment. A message is ready when it is waiting to be processed. Whenever a consumer connects to the queue it receives a batch of messages to process. Meanwhile, the consumer is working on the messages the amount is given in prefetch size and they get the message unacked. RabbitMQ Unacked Messages are the messages that are not Acknowledged.  
> 
> If a consumer fails to acknowledge messages, the RabbitMQ will keep sending new messages until the prefetch value set for the associated channel is equal to the number of RabbitMQ Unacked Messages count. If RabbitMQ Unacked Messages are available then it will make the “struck” messages available again, and the client process will automatically reconnect. RabbitMQ Unacked Messages are read by the consumer but the consumer has never sent an ACK or confirmation to the RabbitMQ broker to say that it has finished processing it.
> 

### Goals

- [ ] Review our use of queues to closer match the patterns expected by RabbitMQ developers.

### Tasks

- [ ] TBD

### Related Resources
[RabbitMQ ChangeLog ](https://www.rabbitmq.com/changelog.html)

Current queue configuration
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/23369849/180200313-4c8ee929-3cd6-47c7-832f-9d2baf793cd2.png">

**Comment by carmenfan** [comment]
as discussed in teams, we could ack the message as soon as we received it, but we will need to requeue a message should the processing failed in an unexpected way, currently there's 2 ways this may happen:

1. Licensing failure - this is easily resolved by code changed as we are in control at the point of failure
2. If the bouncer_worker was terminated unexpectedly, this mostly happens when AWS recalls the machine and the nodeJS application gets killed. Question is, is there anyway the nodeJS can get a signal before this happens so we can requeue a message? Do we get a signal that [we can catch](https://nodejs.org/api/process.html#signal-events) (like SIGTERM?)

**Comment by keifgwinn** [comment]
If the node is going away due to AWS initiated activity, we have the [aws-node-termination-handler](https://github.com/aws/aws-node-termination-handler) installed and currently configured in metadata monitoring mode 
<img width="537" alt="image" src="https://user-images.githubusercontent.com/23369849/180221060-18b230c1-70ec-4fa6-aa9d-cd523218d0d3.png"> so we should get notified that the hardware will be going away.

Currently installed like this
```

#AWS packages, termination handler, cloudwatch metrics  
helm upgrade --install \
 --force aws-node-termination-handler \
 --namespace kube-system \
 --set enableSpotInterruptionDraining="true" \
 --set enableRebalanceMonitoring="true" \
 --set enableScheduledEventDraining="true" \
 --set emitKubernetesEvents="true" \
 --set taintNode="true" \
 eks/aws-node-termination-handler --version 0.13.3

```

 In that event, the nodes get 'tainted' or set that they're going to be offlined, and kubernetes should issue a signal to the pods that they're [getting terminated](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/)  and pods [gracefully shut down](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination) under our current configuration TERM is sent to node

> The kubelet triggers the container runtime to send a TERM signal to process 1 inside each container.

so we should be able to catch it.

However, occasionally there may be a hardware error underneath that will not follow this process.

**Comment by sebjf** [comment]
Hi @carmenfan,

I've discussed with @Charence and @nkuberaf and there is no need from devops to review further how we handle the bouncer queues.

The original rabbitmq ticket linked has been closed.

Though, above you said,

> as discussed in teams, we could ack the message as soon as we received it, but we will need to requeue a message should the processing failed in an unexpected way

Do you recall if there is still a reason to do this? 

(If the rabbitmq issue is resolved then I'd have thought it best not to re-queue a failing model as it will just keep erroring in an endless cycle.)

**Comment by sebjf** [comment]
Thank you @carmenfan!

I think I understand then: we are using manual acknowledgements to make RabbitMQ keep a copy of a message in case bouncer worker or the node goes away before we know the outcome of the task (nothing to do with whether bouncer itself is successful or not).

I've had a bit of a read to try to understand this better, and from this I don't think it is really a bouncer worker issue since the 'problem' is not in how bouncer worker acks messages, but in the architecture of the queues.

In fact, the current docs still suggest the `ack` pattern we are using now, and literally define consumer acknowledgement as signalling a message "was ... received *and processed successfully*".

Quorum Queues as I understand are sets of replicas (`followers`) with a single `leader`, that can self-elect a new leader should the current leader go away. The replicated messages at the followers ensures no messages are lost in case of failure of the leader. The problem with the way we ack messages in this context is that the quorum often likes to perform log compaction, which outstanding acks interferer with.

The thing is though, ultimately if we ack a message before we know the result, it may be deleted from the quorum at any time, and therefore lost if the node goes away (no different to the way classic queues are used atm). The docs don't suggest an alternative pattern - and it seems we aren't the only people to have this issue with long running jobs. (Looks like the general consensus is to build some sort of job management system on top of RabbitMQ.)

This ticket should probably be moved to DevOps to look into further.

Though, the one thing that would be very relevant to check here is that bouncer is idempotent, I have a feeling that it is not 100%...

**Comment by carmenfan** [comment]
agreed.  Quick google suggest we may need a middleman to handle this, so moving this to devops to think about the whole picture https://github.com/3drepo/DevOps/issues/1056
