### ISSUE TITLE
DGN upload bug (ODA Upgrade)

### ISSUE THREAD

**Issue by anorrie** [3drepo/3drepobouncer#592]
### Description

Models uploading via DGN with  multiple views defined in the file are failing to process 

- This is happening in: both 
- This requires a hotfix to production: maybe 

### Steps to replicate
- upload a file - samples here - https://www.dropbox.com/sh/h1uedpj9akrjz1y/AAAiBD_tNTL35L4uUvbQ6Avea?dl=0 
- model will fail with a system error 
- Issue can be resolved by removing some views but will result in a model with no zoom capability? example - https://staging.dev.3drepo.io/viewer/Balfour_Beatty_TEST/6cce8840-6cd2-11ed-beff-055977518cdd 

### Current Behaviour
- models fail 

### Expected Behaviour
- models dont fail

**Comment by carmenfan** [comment]
4 files were provided: 
![image](https://user-images.githubusercontent.com/11945337/205611800-be16f4e2-645d-442a-b788-3c62f740b569.png)

There are 2 problems here:
#### Views
For the file ending with `109968`, there are 3 different views: 
![image](https://user-images.githubusercontent.com/11945337/205612026-517968c1-7e75-45a2-a7e2-3b9cf7a786d2.png)

Our logic finds the first available `DesignModel` view, meaning it has selected the `DesignModel Views`, which has no geometry.  Selecting the `DesignModel-3D` view on the oda app shows a pipe:
![image](https://user-images.githubusercontent.com/11945337/205612511-c371b1fd-ebec-4a1f-a631-523c9c4ff7ae.png)


The ODA api does not distinguish `DesignModel` and `DesignModel-3D`, but there is probably a way we can figure it out and give priority to `DesignModel-3D` and the geometry should come out.

#### Versioning
the other files fail to open on odaDgnApp on the version we're using (it thinks the file is corrupted), however it does open on the latest version of odaDgnApp:
![image](https://user-images.githubusercontent.com/11945337/205613404-b4942c1f-f535-4503-a6e0-205440aad943.png)

So in theory, upgrading ODA to the latest version will work. (This will also allow us to support the latest versions of revit/navis)
Some of these have multiple `DesignModel-3D` view, so we will need to know whether we just take the first available view or we should try to prioritise a specific view name 
![image](https://user-images.githubusercontent.com/11945337/205613778-195ff60e-1f06-494e-b836-8039d1b6fdd5.png)

**Comment by sebjf** [comment]
Hi @carmenfan @anorrie,

I have updated ODA. The DGNs import now. 

One way to distinguish between 2D and 3D views would be to see if any of the extents have zero size.

It seems as those files do have Active views explicitly set (to the 2D views). @anorrie is this the case or is ODA just picking the default as the comments suggest?

I can update it so that it checks if the active view has zero size in any dimension then takes the first DesignModel view that is in 3D, but that would just ignore the users choice if they really wanted a 2D view, is that not a problem?

**Comment by carmenfan** [comment]
> Hi @carmenfan @anorrie,
> 
> I have updated ODA. The DGNs import now.
> 
> One way to distinguish between 2D and 3D views would be to see if any of the extents have zero size.
> 
> It seems as those files do have Active views explicitly set (to the 2D views). @anorrie is this the case or is ODA just picking the default as the comments suggest?
> 
> I can update it so that it checks if the active view has zero size in any dimension then takes the first DesignModel view that is in 3D, but that would just ignore the users choice if they really wanted a 2D view, is that not a problem?

@sebjf I don't think ODA sets the default, the file has a default (in the old days when we don't choose designModel for some models it used to be on the title sheet and some aren't)

is there a way to differentiate `DesignModel` and `DesignModel-3D` ?  since the odaDgnApp has it on the UI I'd imagine there's a way for us to pull that out (their app source code is also provided in the library)

If we can tell the difference then we would just loop through the views and prioritise to the first/default `DesignModel-3D` we find, otherwise the first/default `DesignModel` (unless @anorrie knows there's a convention we should detect for, like 3drepo view on revit)

**Comment by sebjf** [comment]
Hi @carmenfan, 

Are DesignModel and DesignModel-3D 'standardised' names that are common across customers/dgns? 

I thought at first that the OdaDgnApp was generating them automatically as you say, but on looking closer those names are stored explicitly in the file. Other views/models in @anorrie's set have names like "Profile Run - Profile 1 Land Drainage", etc.

> the file has a default

I was worried because the comments for this API said that it "will set to the first available model", but I had another look and they do clarify "(well saving)" so actually it should be possible to detect if a file doesn't have one set. (Do we have a DGN without a default view set so this can be tested?)

However, that's not great because these files provided all have default views set to the non-3D ones! What should we do when the user has chosen a default view but its not 3D?

**Comment by carmenfan** [comment]
> However, that's not great because these files provided all have default views set to the non-3D ones! What should we do when the user has chosen a default view but its not 3D?

@sebjf 
We kind of already do this [here](https://github.com/3drepo/3drepobouncer/blob/master/bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/file_processor_dgn.cpp#L114). At the moment, if the active view is not a `kDesignModel` or it's named title (I think we've had a title sheet that fell into `kDesignModel` before... we loop through all the views and set it to the first available `kDesignModel`

So I think it's just a question of whether it's possible to expand it to check if a `kDesignMode`l is what the dgnApp says `DesignModel` or `DesignModel-3D`, since that enum doesn't seem to distinguish the 2

**Comment by sebjf** [comment]
Hi @carmenfan, we can for sure do that using the Geom Extents parameter.

I am probably being dense, but I still don't see it as a solution though, because the "DesignModel" and "DesignModel-3D" don't actually have anything to do with the enum.

Both these views are of the type `kDesignModel`, but from what I can see that is just a coincidence (maybe the authoring app gave a suggested name of DesignModel, and the user appended the 3D when they saved the second?). So while matching the name would work for these, another customer could call their 3d one DesignModel3D, or PrimaryView, and the the heuristic would break.

Is this not a problem? (Maybe because there is some convention I am not aware of!)

**Comment by carmenfan** [comment]
> Hi @carmenfan, we can for sure do that using the Geom Extents parameter.
> 
> I am probably being dense, but I still don't see it as a solution though, because the "DesignModel" and "DesignModel-3D" don't actually have anything to do with the enum.

No no this is more likely to be me than you as I'm not actually looking at this thing properly 😆 

So what I as assuming is that the 2 columns we see here, the left is the view name and the right is the view type. Are they both just names of some sort? are there any signficance to the right column?
![image](https://user-images.githubusercontent.com/11945337/206678631-dcd630d0-5638-4081-bd59-8c69d89b2a04.png)

If they are all just arbitrary naming it may also be something @anorrie can check with the customers, maybe the column on the right is some sort of naming convention by the CAD software

**Comment by sebjf** [comment]
> so what I was assuming is that the 2 columns we see here, the left is the view name and the right is the view type

That's what I thought but unfortunately not! 

It seems DGN has two distinct entities, View (Groups) and Models, and there is (as far as I can tell) a one way dependency in that Models can own Views/Views are associated with a particular Model. A Model can have default or Active views. The file has an Active Model. (And it is the model that has a type, such as kDesignModel).

The string in the right hand column is the name of the Model to which the View (Group) belongs, and comes from a field, rather than being generated.

It becomes clearer when you look at some of the other files, whose entities have names that don't so closely reflect the types,

![image](https://user-images.githubusercontent.com/5058369/206696649-22d9fbd9-c0a4-4fb6-994b-4a37ffccf15b.png)

**Comment by carmenfan** [comment]
@sebjf gotcha.

In that case then I think the current logic is right, we just need to wait got @anorrie  on the input on whether there should be a model name/view name we should be prioritising.

**Comment by carmenfan** [comment]
@sebjf  can we add a line to output the view name/model name we're trying to import?

We already do it if we manually override the active view, but it will help to just print it even if we didn't change the view to help diagnosing import problems in the future
