### ISSUE TITLE
Autodesk 2024 native support (ODA upgrade)

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#634]

**Comment by sebjf** [comment]
Things that changed this time round:

1. BmViewType Enum has changed location
2. The ParamDef Group Type has changed type
3. The flags for the type of geometry in an OdNwFragment have been removed (the geometry itself must now be tested by casting to the different subclasses)
4. The way the vertex data in an OdNwGeometry is accessed has changed.

Things to check extra carefully:

1. That the built in parameter labels are correct
2. That the view setup in RVT is still correct
3. That both Lines and Meshes still import correctly from Navisworks

**Comment by sebjf** [comment]
Hi @carmenfan, on staging, the Source File entry contains the full filename for a Navisworks entry...

![image](https://github.com/3drepo/3drepobouncer/assets/5058369/85d5a736-d14a-4709-808a-78da9c522fe4)

This line suggests that we intend to only include the filename itself: https://github.com/3drepo/3drepobouncer/blob/15045ef13cce41da7f7a397013f75f651c3941fd/bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_nwd.cpp#L259

However, given the import I just performed, it seems this is not taking effect.

Do you know what the desired behaviour is? (I.e. whether the Source File metadata entry should display the full path or just the filename?)

**Comment by carmenfan** [comment]
> Hi @carmenfan, on staging, the Source File key contains the full filename for a Navisworks entry...
> 
> ![image](https://user-images.githubusercontent.com/5058369/269610061-85d5a736-d14a-4709-808a-78da9c522fe4.png)
> 
> This line suggests that we intend to only include the filename itself:
> 
> https://github.com/3drepo/3drepobouncer/blob/15045ef13cce41da7f7a397013f75f651c3941fd/bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_nwd.cpp#L259
> 
> However, given the import I just performed, it seems this is not taking effect.
> 
> Do you know what the desired behaviour is? (I.e. whether the Source File metadata entry should display the full path or just the filename?)


@sebjf 
I think we only want the file name here, afterall the path to the file isn't very useful in the cloud aimed for collaboration!

**Comment by sebjf** [comment]
Differences accounted for (ongoing):

1. Some display names have more information, e.g. an entry called `327598` is now called `Model Lines_327598`.
2. `OdNwPartition::getDisplayName` now includes the file path; bouncer has been updated to remove it when setting the layer, as this would affect the tree.
3. The `Item::Material` metadata entry has different `Color` values. These are internal implementation details so no change is necessary.
4. Two new items, `Item::Source File Name` and `Item::File Name` have been added, both of which include the full path. The metadata also sometimes includes `Item::Source File` too. A post-processing stage removes the path from the filename for all of these. `Item::Source File Name` has been ignored, since without the path it is identical to `Item::Source File`.
5. The unicode characters for some units have changed (they both displayed correctly before in Chrome, but the new ones are "more correct").
