### ISSUE TITLE
One click compilation with Qt

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepobouncer#9]

**Comment by carmenfan** [comment]
QT supports loading projects with CMake. I just tried this with QTCreator and worked (worked as in it loaded the project and managed to compile the 3drepobouncer.dll).

Essentially you need to do the following to make it work seamlessly if you do the following:
- Set your CMake executable in QT Creator (Tools -> Options -> Build & Run -> CMake(tab))
- File -> open File or project -> select the root level CMakeList.txt and the cmake wizard should pop up.
 
In order to build the 3drepobouncer, you need to set a few env vars, here's mine:
$env:BOOST_ROOT ="C:\local\boost_1_58_0"
$env:BOOST_LIBRARYDIR="C:\local\boost_1_58_0\lib64-msvc-12.0"
$env:MONGO_ROOT ="C:\local\mongo-cxx-driver"
$env:ASSIMP_ROOT ="C:\local\assimp"

so redirect those to your appropriate installations and it should just work fine. These env vars are used to let cmake locate your libraries automatically. If you installed it to linux typical directories (like /usr/local or something) it will auto detect without the need of these. , but you could tamper with the CMakeList.txt on the root directory to redirect it that way.

QT instructions are here: http://doc.qt.io/qtcreator/creator-project-cmake.html


Maybe I should add these stuff on read me!

**Comment by carmenfan** [comment]
Trying to clean up the issues on the bouncer, as this should work fine so I'm closing this. Jozef you can open the issue again if it fails!

**Comment by jozefdobos** [comment]
To set Arguments in Qt creator:
-DBOOST_ROOT="C:\local\boost_1_58_0" -DBOOST_LIBRARYDIR="C:\local\boost_1_58_0\lib64-msvc-12.0"

etc
